//go:build e2e

package e2e

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// TestPipelineSmoke verifies the full init pipeline in a clean temp directory:
// init → check expected output files exist.
func TestPipelineSmoke(t *testing.T) {
	t.Parallel()

	bin := buildBinary(t)
	dir := t.TempDir()

	// Run init with claude-code platform.
	r := runBinary(t, bin, "init", "--dir", dir, "--platforms", "claude-code", "--project", "smoke-test")
	require.Equal(t, 0, r.ExitCode, "init should exit 0: stdout=%s stderr=%s", r.Stdout, r.Stderr)

	// Verify autopus.yaml was created.
	assert.FileExists(t, filepath.Join(dir, "autopus.yaml"), "autopus.yaml should exist after init")

	// Verify .claude/ directory structure.
	assert.DirExists(t, filepath.Join(dir, ".claude"), ".claude/ directory should exist")
	assert.DirExists(t, filepath.Join(dir, ".claude", "rules"), ".claude/rules/ should exist")
	assert.DirExists(t, filepath.Join(dir, ".claude", "rules", "autopus"), ".claude/rules/autopus/ should exist")

	// Verify CLAUDE.md was generated.
	claudeMD := filepath.Join(dir, "CLAUDE.md")
	assert.FileExists(t, claudeMD, "CLAUDE.md should be generated by init")

	data, err := os.ReadFile(claudeMD)
	require.NoError(t, err)
	assert.Contains(t, string(data), "autopus", "CLAUDE.md should reference autopus")
}
